name: Cypress Tests

on:
  push:
    branches: [master, develop]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4] # número de máquinas en paralelo
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'https://site6.q10.com/'
          record: true
          parallel: true
          group: 'UI Tests'  # nombre del grupo en Cypress Cloud
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}